repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        name: ruff-pre-commit
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        types_or: [python, pyi]

